### ISSUE TITLE
Add PWA download banner for desktop course page

### ISSUE THREAD

**Issue by annarhughes** [chaynHQ/bloom-frontend#1209]
### Overview

Bloom is a PWA app which means it can be installed/downloaded as a browser app. We previously didn't promote this feature, so most users would be unaware that the app can be installed using the browser button. We added a mobile PWA banner in #1207.

This is an adjacent task to #1207 and involves adding a similar banner to the `/courses` page. This banner will only be shown for authenticated users who signed up 2+ weeks ago. Note that there will be duplication with code from #1207 and this should be reused and refactored as required.

Note that iOS doesn't support have a function to trigger installing the app, so we instead show an extra description instructing iOS users how to install the app. 

There are subsequent PWA tasks linked to the [PWA epic issue](#1197).

### Design
This is the banner shown for all browsers
<img width="806" alt="Screenshot 2024-11-19 at 17 16 14" src="https://github.com/user-attachments/assets/41c639cc-084d-40fa-8544-3e7d47626d52">

This is the banner shown for iOS users after clicking the "Install" button

![desktop_pwa_ios_banner](https://github.com/user-attachments/assets/40080c86-3adc-413f-b019-62476f5ccf6c)

### Action Items

- [ ] Create the UI components e.g. `PWABanner` in `components/banner`
- [ ] Reuse functionality for installing the app for chromium-based browsers and iOS, as is done in `NavigationPWABanner` in #1207 
- [ ] Add functionality/UI explaining how to install the app on iOS browsers, similar to #1207
- [ ] Add functionality for the "Not now" dismiss button, as in #1207 
- [ ] Add functionality that only shows this banner for users who have an account and signed up 2+ weeks ago

### Resources/Instructions

See the resources below for more on PWAs.

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Trigger_install_prompt
https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/
https://www.freecodecamp.org/news/what-are-progressive-web-apps/

**Comment by MartinGodzina** [comment]
I’d be interested in working on this 😊 I previously implemented the mobile PWA banner #1207 , so I’m happy to extend the support to desktop as well.

**Comment by kyleecodes** [comment]
@MartinGodzina any updates? No worries if you need more time, especially since you already contributed to the PWA banner. Asking in case you have moved on so we can open up the issue. Thanks!

**Comment by MartinGodzina** [comment]
@kyleecodes Sorry, I totally missed that one! I'll have a merge ready in the next 1–2 days.
